# Generated by Django 3.1.7 on 2021-03-15 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500)),
                ('mark', models.FloatField()),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=1)),
                ('grade', models.CharField(max_length=2)),
                ('year', models.CharField(max_length=4)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='student_management.student')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
